### ISSUE TITLE
Problems during runmod

### ISSUE THREAD

**Issue by luizalex** [crashub/mod-shell#2]
I`ve problems with runmod. The log (as bellow) indicates a missing class  org/apache/mina/core/service/IoAcceptor, but the lib (mina-core-2.0.4.jar) exists on mods/lib. Any ideia about what is wrong?

(console output)
$ vertx runmod org.crashub~mod-shell~2.0.0-SNAPSHOT -conf conf.json

Loaded plugin Plugin[type=CRaSHShellFactory,interface=ShellFactory] 
Loaded plugin Plugin[type=ProcessorIOHandler,interface=TermIOHandler] 
Loaded plugin Plugin[type=JaasAuthenticationPlugin,interface=AuthenticationPlugin] 
Loaded plugin Plugin[type=SimpleAuthenticationPlugin,interface=AuthenticationPlugin] 
Loaded plugin Plugin[type=SSHPlugin,interface=SSHPlugin] 
Loaded plugin Plugin[type=SSHInlinePlugin,interface=CommandPlugin] 
Loaded plugin Plugin[type=KeyAuthenticationPlugin,interface=KeyAuthenticationPlugin] 
Configuring property auth.simple.username=admin from properties 
Configuring property auth.simple.password=admin from properties 
Configuring property ssh.port=2000 from properties 
Configuring property auth=simple from properties 
Initialized plugin Plugin[type=CRaSHShellFactory,interface=ShellFactory] 
Initialized plugin Plugin[type=ProcessorIOHandler,interface=TermIOHandler] 
Initialized plugin Plugin[type=JaasAuthenticationPlugin,interface=AuthenticationPlugin] 
Initialized plugin Plugin[type=SimpleAuthenticationPlugin,interface=AuthenticationPlugin] 
Initialized plugin Plugin[type=KeyAuthenticationPlugin,interface=KeyAuthenticationPlugin] 
Booting SSHD 
Could not start CRaSSHD 
java.lang.NoClassDefFoundError: org/apache/mina/core/service/IoAcceptor
    at org.crsh.ssh.term.SSHLifeCycle.doInit(SSHLifeCycle.java:107)
    at org.crsh.term.TermLifeCycle.init(TermLifeCycle.java:42)
    at org.crsh.ssh.SSHPlugin.init(SSHPlugin.java:131)
    at org.crsh.plugin.PluginManager.getPlugins(PluginManager.java:83)
    at org.crsh.plugin.PluginContext.start(PluginContext.java:321)
    at org.crsh.plugin.PluginLifeCycle.start(PluginLifeCycle.java:96)
    at org.vertx.mods.VertxPluginLifeCycle.start(VertxPluginLifeCycle.java:83)
    at org.vertx.mods.CRaSHBusMod.start(CRaSHBusMod.java:16)
    at org.vertx.java.platform.Verticle.start(Verticle.java:82)
    at org.vertx.java.platform.impl.DefaultPlatformManager$18.run(DefaultPlatformManager.java:1278)
    at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:170)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:366)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
    at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.ClassNotFoundException: org.apache.mina.core.service.IoAcceptor
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.vertx.java.platform.impl.ModuleClassLoader.loadClass(ModuleClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 15 more

Initialized plugin Plugin[type=SSHPlugin,interface=SSHPlugin] 
Initialized plugin Plugin[type=SSHInlinePlugin,interface=CommandPlugin]

**Comment by luizalex** [comment]
Solved. I should compile the project (mod-shell) with java 1.7.

**Comment by vietj** [comment]
that reminds me I should do a proper 2.0 release
