### ISSUE TITLE
-f JSON for 'bus publish'

### ISSUE THREAD

**Issue by darylteo** [crashub/mod-shell#8]
Send works, but can't seem to get this working for publish.

``` shell
> bus publish -f JSON :event:service-up {"serviceId":"hello"}
> bus publish -f JSON :event:service-up {"serviceId":"hello"}: Missing argument address
```

---

Edit: just realised that it is supposed to send it as JSON based on the help message: However, on my end i get this:

```
bus publish :event:service-up {"serviceId":"hello"} 
```

``` java
java.lang.ClassCastException: java.lang.String cannot be cast to org.vertx.java.core.json.JsonObject
    at com.darylteo.vertx.vas.core.eventbus.Messaging.lambda$subscribe$1(Messaging.java:102)
    at com.darylteo.vertx.vas.core.eventbus.Messaging$$Lambda$1/1504400865.handle(Unknown Source)
    at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:943)
    at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
    at java.lang.Thread.run(Thread.java:744)
```

---

Edit: reading the source, it does seem that you are sending a JsonObject. I just can't fathom why it is receiving it as a String on the receiving end. 

Regards,
Daryl

**Comment by vietj** [comment]
Fixed by 3b63abc049a28214dc2f29e58591b6880bbdf000
